### ISSUE TITLE
proposal kan overzichtelijker

### ISSUE THREAD

**Issue by stgm** [lijdsmanalwin/DesktopCFO#2]
als allereerst even heel goed duidelijk maken wat je gaat maken en hoe het er ongeveer uit gaat zien

**Comment by lijdsmanalwin** [comment]
Ik heb nu bovenaan een duidelijk voorbeeld gegeven van wat de app doet. Helpt dit? Ik heb het idee dat het overzicht kwijt raakt door de grote plaatjes van de andere apps onderin. In de schets staat hoe het er precies uit moet zien. Kan ik deze schetsen beter groter maken?

**Comment by lijdsmanalwin** [comment]
Ik heb mijn sketch nu ook aangepast! Hopelijk is het zo duidelijker
